# Generated by Django 3.1.4 on 2020-12-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_manager',
            new_name='is_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_supervisor',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
